import pandas as pd

data = pd.DataFrame(
    {
        "symptom1": [
            # Respiratory (Rows 1-12)
            "fever",
            "cough",
            "sore throat",
            "fever",
            "cough",
            "shortness of breath",
            "fever",
            "chest pain",
            "cough",
            "fatigue",
            "night sweats",
            "persistent cough",
            # Gastrointestinal (Rows 13-20)
            "nausea",
            "vomiting",
            "diarrhea",
            "stomach pain",
            "abdominal pain",
            "nausea",
            "heartburn",
            "loss of appetite",
            # Neurological (Rows 21-28)
            "headache",
            "dizziness",
            "confusion",
            "blurry vision",
            "headache",
            "tinnitus",
            "numbness",
            "migraine",
            # Musculoskeletal (Rows 29-36)
            "joint pain",
            "muscle pain",
            "back pain",
            "joint stiffness",
            "muscle weakness",
            "neck pain",
            "knee pain",
            "hip pain",
            # Cardiovascular (Rows 37-42)
            "chest tightness",
            "palpitations",
            "shortness of breath",
            "swollen ankles",
            "fatigue",
            "dizziness",
            # Dermatological (Rows 43-48)
            "itchy skin",
            "rash",
            "dry skin",
            "skin redness",
            "hives",
            "blisters",
            # Urogenital (Rows 49-56)
            "painful urination",
            "frequent urination",
            "blood in urine",
            "pelvic pain",
            "irregular periods",
            "heavy bleeding",
            "vaginal itching",
            "testicular pain",
            # ENT (Rows 57-64)
            "runny nose",
            "sneezing",
            "itchy eyes",
            "ear pain",
            "hearing loss",
            "nosebleeds",
            "loss of taste",
            "loss of smell",
            # Mental Health & Other (Rows 65-72)
            "insomnia",
            "anxiety",
            "fatigue",
            "hair loss",
            "cold hands",
            "bruising",
            "night sweats",
            "weight gain",
        ],
        "symptom2": [
            # Respiratory
            "cough",
            "fever",
            "fever",
            "fatigue",
            "wheezing",
            "wheezing",
            "chills",
            "cough",
            "sputum",
            "night sweats",
            "weight loss",
            "weight loss",
            # Gastrointestinal
            "vomiting",
            "diarrhea",
            "cramping",
            "nausea",
            "bloating",
            "fatigue",
            "regurgitation",
            "weight loss",
            # Neurological
            "nausea",
            "vertigo",
            "slurred speech",
            "headache",
            "light sensitivity",
            "hearing loss",
            "tingling",
            "vomiting",
            # Musculoskeletal
            "morning stiffness",
            "fatigue",
            "leg pain",
            "swelling",
            "fatigue",
            "shoulder pain",
            "swelling",
            "stiffness",
            # Cardiovascular
            "shortness of breath",
            "anxiety",
            "cough",
            "shortness of breath",
            "swollen ankles",
            "chest pain",
            # Dermatological
            "rash",
            "itching",
            "scaling",
            "swelling",
            "swelling",
            "pain",
            # Urogenital
            "frequency",
            "urgency",
            "back pain",
            "painful periods",
            "pelvic pain",
            "clotting",
            "discharge",
            "swelling",
            # ENT
            "sneezing",
            "runny nose",
            "red eyes",
            "fever",
            "tinnitus",
            "headache",
            "fatigue",
            "congestion",
            # Mental Health & Other
            "anxiety",
            "restlessness",
            "depression",
            "scalp itching",
            "color changes",
            "bleeding gums",
            "fever",
            "fatigue",
        ],
        "symptom3": [
            # Respiratory
            "fatigue",
            "runny nose",
            "difficulty swallowing",
            "body aches",
            "chest tightness",
            "coughing",
            "cough",
            "fever",
            "shortness of breath",
            "cough",
            "cough",
            "chest pain",
            # Gastrointestinal
            "dehydration",
            "stomach pain",
            "fever",
            "bloating",
            "constipation",
            "pale skin",
            "chest pain",
            "weakness",
            # Neurological
            "sensitivity to light",
            "nausea",
            "facial drooping",
            "eye pain",
            "neck pain",
            "ear fullness",
            "muscle spasms",
            "aura",
            # Musculoskeletal
            "fatigue",
            "joint pain",
            "numbness",
            "redness",
            "tingling",
            "arm pain",
            "locking",
            "difficulty walking",
            # Cardiovascular
            "palpitations",
            "sweating",
            "wheezing",
            "weight gain",
            "shortness of breath",
            "fainting",
            # Dermatological
            "dry skin",
            "flaking",
            "cracking",
            "warmth",
            "itching",
            "oozing",
            # Urogenital
            "pain",
            "burning",
            "nausea",
            "back pain",
            "mood swings",
            "fatigue",
            "irritation",
            "lump",
            # ENT
            "watery eyes",
            "congestion",
            "swollen eyes",
            "drainage",
            "balance issues",
            "bruising",
            "weight loss",
            "headache",
            # Mental Health & Other
            "racing thoughts",
            "panic",
            "brain fog",
            "brittle nails",
            "numbness",
            "easy bruising",
            "chills",
            "cold intolerance",
        ],
        "disease": [
            # Respiratory
            "Influenza",
            "Common Cold",
            "Strep Throat",
            "Influenza",
            "Asthma",
            "Asthma",
            "Pneumonia",
            "Pneumonia",
            "Bronchitis",
            "Tuberculosis",
            "Tuberculosis",
            "Lung Cancer",
            # Gastrointestinal
            "Gastroenteritis",
            "Gastroenteritis",
            "Gastroenteritis",
            "Gastritis",
            "IBS",
            "Celiac Disease",
            "GERD",
            "Stomach Cancer",
            # Neurological
            "Migraine",
            "Vertigo",
            "Stroke",
            "Migraine",
            "Tension Headache",
            "Meniere Disease",
            "Neuropathy",
            "Cluster Headache",
            # Musculoskeletal
            "Rheumatoid Arthritis",
            "Fibromyalgia",
            "Sciatica",
            "Osteoarthritis",
            "Multiple Sclerosis",
            "Cervical Spondylosis",
            "Meniscus Tear",
            "Osteoporosis",
            # Cardiovascular
            "Angina",
            "Arrhythmia",
            "Heart Failure",
            "Heart Failure",
            "Anemia",
            "Hypotension",
            # Dermatological
            "Eczema",
            "Contact Dermatitis",
            "Psoriasis",
            "Cellulitis",
            "Urticaria",
            "Shingles",
            # Urogenital
            "UTI",
            "UTI",
            "Kidney Stones",
            "Endometriosis",
            "PCOS",
            "Uterine Fibroids",
            "Yeast Infection",
            "Testicular Torsion",
            # ENT
            "Allergic Rhinitis",
            "Allergic Rhinitis",
            "Allergic Conjunctivitis",
            "Otitis Media",
            "Otosclerosis",
            "Epistaxis",
            "COVID-19",
            "Sinusitis",
            # Mental Health & Other
            "Insomnia",
            "Anxiety Disorder",
            "Depression",
            "Alopecia",
            "Raynaud Disease",
            "Leukemia",
            "Lymphoma",
            "Hypothyroidism",
        ],
        "cause": [
            # Respiratory
            "Virus",
            "Virus",
            "Bacteria",
            "Virus",
            "Allergy",
            "Allergy",
            "Bacteria",
            "Bacteria",
            "Virus",
            "Bacteria",
            "Bacteria",
            "Genetic/Risk Factors",
            # Gastrointestinal
            "Virus",
            "Virus",
            "Virus/Bacteria",
            "H. pylori",
            "Stress/Diet",
            "Autoimmune",
            "Diet/Lifestyle",
            "Genetic/Helicobacter",
            # Neurological
            "Neurological",
            "Inner Ear",
            "Blood Clot",
            "Neurological",
            "Muscle Tension",
            "Inner Ear Fluid",
            "Diabetes/Autoimmune",
            "Neurological",
            # Musculoskeletal
            "Autoimmune",
            "Central Nervous System",
            "Herniated Disc",
            "Wear and Tear",
            "Autoimmune",
            "Degenerative",
            "Injury",
            "Bone Density Loss",
            # Cardiovascular
            "Artery Blockage",
            "Electrical Disorder",
            "Weak Heart Muscle",
            "Weak Heart Muscle",
            "Iron Deficiency",
            "Low Blood Pressure",
            # Dermatological
            "Genetics/Environment",
            "Irritant",
            "Autoimmune",
            "Bacteria",
            "Allergen",
            "Virus",
            # Urogenital
            "Bacteria",
            "Bacteria",
            "Mineral Buildup",
            "Hormonal",
            "Hormonal",
            "Hormonal",
            "Fungus",
            "Twisting",
            # ENT
            "Allergen",
            "Allergen",
            "Allergen",
            "Bacteria",
            "Genetic",
            "Dry Air/Trauma",
            "Virus",
            "Virus/Bacteria",
            # Mental Health & Other
            "Stress",
            "Chemical Imbalance",
            "Chemical Imbalance",
            "Autoimmune",
            "Vascular",
            "Bone Marrow",
            "Lymph System",
            "Autoimmune",
        ],
        "prevention": [
            # Respiratory
            "Vaccine, hand washing",
            "Hand hygiene",
            "Complete antibiotics",
            "Rest, fluids",
            "Avoid triggers",
            "Avoid allergens",
            "Vaccine, no smoking",
            "Vaccine",
            "No smoking",
            "Ventilation, vaccine",
            "Early treatment",
            "No smoking",
            # Gastrointestinal
            "Wash hands",
            "Hydration",
            "Clean food/water",
            "Avoid NSAIDs",
            "Manage stress",
            "Gluten-free diet",
            "Small meals",
            "Screening, healthy diet",
            # Neurological
            "Avoid triggers",
            "Avoid rapid movements",
            "Control BP",
            "Rest, dark room",
            "Stress management",
            "Low salt",
            "Manage diabetes",
            "Avoid triggers",
            # Musculoskeletal
            "Early treatment",
            "Exercise, sleep",
            "Good posture",
            "Joint protection",
            "No prevention",
            "Ergonomics",
            "Strengthen muscles",
            "Calcium, exercise",
            # Cardiovascular
            "Healthy diet",
            "Limit caffeine",
            "Low sodium",
            "Low sodium",
            "Iron-rich foods",
            "Hydration",
            # Dermatological
            "Moisturize",
            "Avoid irritants",
            "Stress management",
            "Wound care",
            "Avoid allergens",
            "Vaccine",
            # Urogenital
            "Hygiene, water",
            "Cranberry juice",
            "Hydration",
            "No prevention",
            "Healthy weight",
            "No prevention",
            "Hygiene",
            "Immediate care",
            # ENT
            "Avoid allergens",
            "Avoid allergens",
            "Avoid allergens",
            "Vaccine",
            "Noise protection",
            "Humidifier",
            "Mask, distancing",
            "Nasal irrigation",
            # Mental Health & Other
            "Sleep schedule",
            "Therapy, meditation",
            "Exercise, therapy",
            "No prevention",
            "Keep warm",
            "No prevention",
            "No prevention",
            "Iodine intake",
        ],
    }
)


print(f"Total Rows: {len(data)}")
print(f"Unique Diseases: {data['disease'].nunique()}")
print(f"\nFirst 5 rows:")
print(data.head())

# Save to CSV
# data.to_csv('disease_prediction_dataset.csv', index=False)
